### ISSUE TITLE
Check in install_via_apt.pl if essential dependencies get overwritten or are still present in there required version

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#193] opened 2021-03-03 07:43 UTC
Background:
- We compile the UDFClient against python and use numpy and pandas and others. 
- Changing versions of these essential dependencies, often leads to broken containers

Acceptance Criteria:
- Flavor steps need to store essentials dependencies, their versions and the installation method in files in the container
- Per default check in install_via_apt.pl if these essential versions get modified and fail
- Have option to overwrite the check and only print a warning

**Comment by redcatbear** [comment] 2023-04-14 07:15
Closing this as a duplicate of #192. @tkilias, is this a c&p error? Did you intend to change the content of the second issue?

**Closed by redcatbear** 2023-04-14 07:15 UTC
Labels: duplicate
